spring:
  config:
    import:
      - database.yml
      - redis.yml
      - mail.yml
      - jwt.yml
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "org.example.coursemanagementsystem.dto.kafka"

server:
  port: 8081

jwt:
  secret: your-256-bit-secret-key-here-min-32-chars
  access-token-expiration: 3600000      # 1 saat (ms)
  refresh-token-expiration: 86400000